### ISSUE TITLE
How exactly is the 10 token per bit implemented?

### ISSUE THREAD

**Issue by remem123** [lancopku/codable-watermarking-for-llm#5]
您好！还是想请教一下您论文中所说的10 token per bit具体是如何实现的呢？
如果是将m转化为二进制比特信息的话，意思是10 token嵌入一个比特吗？
但是看算法2的伪算法好像直接使用映射后的m的整个值去生成的seed(`s = h(ˆh(m), t:(l−1)))`)，然后进行的shuffle操作。如果是通过这种方式的话，又怎么去做到一个比特一个比特的嵌入？

**Comment by leanwang326** [comment]
实际上是200token嵌入一个20bit的message这样子；如果再多的话可以是每200个token独立地来一次20bit嵌入。这儿200token嵌入一次，是为了防止10token嵌入地时候，有些10token可能难嵌入，导致该bit直接失效，从而整个message也就错了

**Comment by remem123** [comment]
所以差不多是200个token，使用一次20个bit的message来生成一个s，进行shuffle操作，然后实现水印文本生成是吗？这样操作的话我们是不是只能从生成的水印文本里面确定是否有水印，而不能直接提取出这个多比特message？我可能理解有点偏差QAQ（老师您这里的多比特message我可以理解为KGW算法中划分红绿列表的key吗）
